require 'rack/oauth2'

class FacebookController < ApplicationController
  before_filter :require_authentication, :only => :destroy

  rescue_from Rack::OAuth2::Client::Error, :with => :oauth2_error

  # handle Facebook Auth Cookie generated by JavaScript SDK
  def show
    auth = Facebook.auth.from_cookie(cookies)
    authenticate Facebook.identify(auth.user)
    redirect_to dashboard_url
  end

  # handle Normal OAuth flow: start
  def new
    client = Facebook.auth(callback_facebook_url).client
    redirect_to client.authorization_uri(
      :scope => [:friends_photos, :friends_relationship_details, :friends_relationships, :user_photos, :user_relationship_details, :user_relationships]
    )
  end

  # handle Normal OAuth flow: callback
  def create
    client = Facebook.auth(callback_facebook_url).client
    client.authorization_code = params[:code]
    access_token = client.access_token! :client_auth_body
    
    $fb_access_token = access_token
    
    user = FbGraph::User.me(access_token).fetch
    redirect_to :controller => 'pictures'
  end

  private

  def callback_facebook_url
    'http://localhost:3000/facebook/create'
  end

  def oauth2_error(e)
    flash[:error] = {
      :title => e.response[:error][:type],
      :message => e.response[:error][:message]
    }
    redirect_to root_url
  end
end
# require 'rack/oauth2'
# 
# class FacebookController < ApplicationController
# 
#   before_filter :init
# 
#   def setup
#     @@a = 1
#     @client.redirect_uri = 'http://localhost:3000/facebook/callback'
#     # redirect user to facebook
#     redirect_to @client.authorization_uri(
#       :scope => [:email, :read_stream, :offline_access]
#     )
#   end
#   
#   def callback
# 
#     # in callback
#     @client.authorization_code = params[:code]
#     access_token = @client.access_token! :client_auth_body # => Rack::OAuth2::AccessToken
#     FbGraph::User.me(access_token).fetch # => FbGraph::User
#     debugger
#     x=1
#   end
# 
# private
# 
#   def init
#     @fb_auth = FbGraph::Auth.new('148302408644162', :secret => '290c5678ab21bdf4e0778fae15012abe', :redirect_uri => 'http://localhost:3000/facebook/callback')
# 
#     # setup client
#     @client = @fb_auth.client
#   end
# 
# end
